支持快捷键查单词
maicss/chrome-shanbay-v2 pull request #15
Opened 2023-11-07 14:01 UTC by rust17

- 支持在 chrome 扩展-自定义快捷键界面设置扇贝查单词快捷键，然后通过快捷键唤起插件查单词，效果：

<img width="1059" alt="image" src="https://github.com/maicss/chrome-shanbay-v2/assets/16575052/67ab1ae7-7b98-4610-a05c-88b01a8440a8">
 
<img width="501" alt="image" src="https://github.com/maicss/chrome-shanbay-v2/assets/16575052/c0607b67-b643-43e4-9c6c-5da1a64cd388">

2023-11-09 16:36 UTC, maicss requested changes

2023-11-09 16:36 UTC, maicss commented on js/background.js
> +const LookUpBySelection = async (tabId) => {
不是类不要首字母大写

2023-11-09 16:36 UTC, maicss commented on manifest.json
> +        "*://*.hjenglish.com/*",
这俩删了是为什么？

2023-11-10 04:49 UTC, rust17 commented on js/background.js
> +const LookUpBySelection = async (tabId) => {
OK，我调整一下

2023-11-10 04:50 UTC, rust17 commented on manifest.json
> +        "*://*.hjenglish.com/*",
这是因为行尾有两个空格，我这边去掉了，需要保留吗

2023-11-10 05:25 UTC, maicss commented on manifest.json
> +        "*://*.hjenglish.com/*",
需要的，这个是用来标记在这些网站不使用这些脚本的。比如shanbay网站上有选中查词了。

2023-11-10 05:56 UTC, rust17 commented on manifest.json
> +        "*://*.hjenglish.com/*",
> 需要的，这个是用来标记在这些网站不使用这些脚本的。比如shanbay网站上有选中查词了。

我的意思是需要保留这两个空格吗，因为我感觉这少了两个空格不影响程序的运行，所以去除掉了，这两行内容并没有删掉

2023-11-10 06:37 UTC, maicss commented on manifest.json
> +        "*://*.hjenglish.com/*",
空格不需要，可以删 😂

2023-11-10 07:01 UTC, maicss commented on manifest.json
> +        "*://*.hjenglish.com/*",
哦哦，我刚明白，是我看错了，你只是删了俩空格。那这里不需要修改了。My bad, sorry.

2023-11-10 12:21 UTC, rust17 commented on js/background.js
> +const LookUpBySelection = async (tabId) => {
已调整哈

2023-11-10 14:04 UTC, maicss commented
谢谢你的贡献 💯

2023-11-10 14:04 UTC, merged